title = "ALD ALE 2026"
body = """
Professor Christophe Vallee will serve as the ALE chair at the [ALD/ALE 2026 conference](https://ald2026.avs.org/) in Tampa between the 28th of June and the 1st of July.
"""
date = 2025-06-25
