title = "Anthony's Publication Highlighted in Surface Science Spectra"
body = """
PhD student Anthony Valenti's [recent publication](https://doi.org/10.1116/6.0005348) in Surface Science Spectra has been selected as a featured article.
"""
date = 2026-07-31
