title = "ASD 2026"
body = """
We are proud to announce that we will be hosting the 2026 edition of the Area Selective Deposition Workshop.
The workshop will be held in Albany, NY, between March 29 and April 1, 2026.
Learn more about the workshop and register [here](https://asd2026.avs.org).
"""
date = 2025-03-27
