title = "UVM Physics Colloquium"
body = """
Professor Christophe Vallee will be giving a talk at the University of Vermont Physics Colloquium regarding atomic-layer processes on October 12th.
"""
date = 2026-09-15
