title = "Dry Process School 2026"
body = """
Professor Chrisophe Vallee will be delivering a lecture on atomic-layer processes at the Dry Process School 2026 taking place in Tokyo, Japan between November 16th and 18th.
"""
date = 2026-05-11
