title = "Dry Process Symposium 2026"
body = """
PhD student Enzo Novoselic will be presenting a poster on area-selective deposition and etching at the Dry Process Symposium 2026 in Tokyo, Japan between November 19th and 20th.
"""
date = 2026-09-18
