title = "Gaseous Electronic Conference 2026"
body = """
Professor Christophe Vallee will be giving an invited talk at GEC 2026 (November 2nd-6th 2026, Chicago, USA) on selectivity in radical plasma processes.
"""
date = 2026-09-10
