title = "Albany Nanotech Symposium 2026"
body = """
Gwanghoon Lee will be presenting his work on studying the impact of ions on PEALD thin films at the Albany Nanotech Symposium 2026 (October 22nd~23rd, 2026, Albany, USA).
"""
date = 2026-08-27
