title = "Colloquium Series"
body = """\
Dr Tojo Rasoanarivo will be presenting at the DNSE Friday Colloquium on Friday September 25th.
He will be presenting on how modelling could help to deepen the understanding of plasma and atomic-scale processes.
"""
date = 2026-09-23
