title = "Core-level high-resolution XPS spectra of trimethylsilyl-functionalized SiO2 surfaces"
doi = "10.1116/6.0005348"
journal = "Surface Science Spectra"
date = 2026-05-19

et_al = true

[[authors]]
card = "anthony_valenti"

[[authors]]
card = "christophe_vallee"
