title = "Conductive TiN thin films grown by plasma-enhanced atomic layer deposition: Effects of N-sources and thermal treatments"
doi = "10.1116/6.0002288"
journal = "JVST-A"
date = 2023-03-06

et-al = true

[[authors]]
first = "Clémence"
last = "Badie"

[[authors]]
card = "christophe_vallee"
