title = "Self-Saturated Deposition and Etching in Atomic-Scale (SDEA) Process of Molybdenum Oxides via Sequential Ozone and Water Reactions"
doi = "10.1002/admt.202500964"
journal = "Advanced Materials Technologies"
date = 2025-08-17

[[authors]]
first = "Chaeyeong"
last = "Hwang"

[[authors]]
first = "Seungwoo"
last = "Lee"

[[authors]]
first = "Soo Min"
last = "Yoo"

[[authors]]
card = "christophe_vallee"

[[authors]]
first = "Woojin"
last = "Jeon"
