title = "Area selective deposition using alternate deposition and etch super-cycle strategies"
doi = "10.1039/d1dt03456a"
journal = "Dalton Transactions"
date = 2021-11-16

et-al = true

[[authors]]
first = "Marceline"
last = "Bonvalot"

[[authors]]
card = "christophe_vallee"
