title = "Integrating area-selective catalytic PMMA etching with PMMA-inhibited area-selective deposition of HfO2"
doi = "10.1116/6.0005630"
journal = "JVST-A"
date = 2026-09-01

[[authors]]
card = "enzo_novoselic"

[[authors]]
card = "natalya_tokranova"

[[authors]]
card = "christophe_vallee"
