title = "Study of selective etching of TaN with respect to SiOCH dielectrics using SiF4 plasma processes"
doi = "10.35848/1347-4065/ad6f85"
journal = "Japanese Journal of Applied Physics"
date = 2024-09-04

[[authors]]
card = "ivo_otto"

[[authors]]
card = "christophe_vallee"
