title = "Selective physisorption ALD-like process and selective PECVD process for smoothing metal organic resist using SO2"
doi = "10.1116/6.0005554"
journal = "JVST-A"
date = 2026-09-03

[[authors]]
card = "nicolas_maldonado"

[[authors]]
card = "van-long_nguyen"

[[authors]]
card = "christophe_vallee"

[[authors]]
first = "Gregory"
last = "Denbeaux"
