title = "Area selective PECVD on metal oxide resist"
doi = "10.1116/6.0004072"
journal = "JVST-A"
date = 2025-02-18

[[authors]]
card = "rosanna_robert"

[[authors]]
first = "Katie"
last = "Lutker-Lee"

[[authors]]
card = "christophe_vallee"
