title = ""
bio = "Focuses on the selective deposition of high-k materials."
position = "phd"
join_year = 2025
orcid = ""
email = "dmacleod@albany.edu"
linkedin = "https://www.linkedin.com/in/doug-macleod-9bb482400/"

[name]
first = "Douglas"
last = "MacLeod"

[highest_degree]
degree = "B.S. Nanoscale Science"
from = "SUNY Albany"
year = 2025
