title = ""
bio = "Focuses on the selective deposition of NbN by ALD."
position = "masters"
join_year = 2026
email = "dpham@albany.edu"

[name]
first = "Dung"
last = "Pham"

[highest_degree]
degree = "B.S."
from = ""
year = 2026
