title = ""
bio = """
Focuses on the intersection of sustainability and cryogenic technologies.
"""
position = "phd"
join_year = 2024
orcid = "0009-0007-6740-0059"
email = "ejournetnovoselic@albany.edu"
linkedin = "https://www.linkedin.com/in/enzo-novoselic"

[name]
first = "Enzo"
last = "Novoselic"

[highest_degree]
degree = "M.S. Nanoscale Engineering"
from = "SUNY Albany"
year = 2026
