title = ""
bio = "Focuses on understanding the impact of positive ions in conformal plasma ALD processes."
position = "undergraduate"
join_year = 2026
email = "glee22@albany.edu"

[name]
first = "Gwanghoon"
last = "Lee"
