title = ""
bio = ""
position = "undergraduate"
join_year = 2026
orcid = ""
email = "jblaylock@albany.edu"
linkedin = "https://www.linkedin.com/in/jacob-blaylock-382300307/"

[name]
first = "Jacob"
last = "Blaylock"
