title = ""
bio = ""
position = "phd"
join_year = 2022
orcid = "0000-0003-4154-0014"
linkedin = "https://www.linkedin.com/in/paul-nicolas-maldonado-pinos-255a46273"

[name]
first = "Nicolas"
last = "Maldonado Pinos"

[highest_degree]
degree = "B.S."
from = ""
year = 2022
