title = ""
bio = "Focuses on understanding plasma-surface interactions in ion-beam-based processes."
position = "phd"
join_year = 2026
orcid = ""

[name]
first = "Simon"
last = "Roemig"

[highest_degree]
degree = "B.S. Materials Science and Engineering"
from = "UWisconsin-Madison"
year = 2023
