title = ""
bio = "Focuses on understanding plasma-surface interactions in ion-beam-based processes."
position = "phd"
join_year = 2026
orcid = ""
linkedin = "linkedin.com/in/simon-roemig-8284521a1"
email = "sroemig@albany.edu"

[name]
first = "Simon"
last = "Roemig"

[highest_degree]
degree = "B.S. Materials Science and Engineering"
from = "UWisconsin-Madison"
year = 2023
