title = ""
bio = "Focused on the dry development of new-generation EUV resists."
position = "postdoc"
alumni = true
join_year = 2020
leave_year = 2021
orcid = "0009-0003-0896-3709"
linkedin = "https://www.linkedin.com/in/steven-grzeskowiak-profile/"

[name]
first = "Steven"
last = "Grzeskowiak"
