title = ""
bio = ""
position = "undergraduate"
join_year = 2026
linkedin = "https://www.linkedin.com/in/zane-schulties-b8a595397/"
email = "zschulties@albany.edu"

[name]
first = "Zane"
last = "Schulties"
