title = "Atomic Scale Processing"
description = """
With ever-shrinking dimensions for modern semiconductor devices, atomic level control has become a requirement for advanced processing.
The following processes are currently being explored:
* Thermal Atomic Layer Deposition (ALD)
* Plasma-Enhanced Atomic Layer Deposition (PEALD)
* Atomic Layer Etching (ALE)
* Atomic Layer Smoothing
* Atomic Layer Cleaning
* etc
"""
order = 2

[[highlight]]
card = "christophe_korea_2025"

[[highlight]]
card = "christophe_tin_2023"

[[highlight]]
card = "christophe_cycles_2021"
