# Used for the announcements banner.

text = "" # Single line of text which will be hyperlinked with the link below.

[link]
url = ""
internal = false
# Internal link structure:
# "home" -> homepage
# "news/article.toml" -> article card on the news page
# "papers/paper.toml" -> publication card on the publications page

[dates] # Format: YYYY-MM-DD
start = 2000-01-01
end = 2000-01-02
